<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Articles <small>header small text goes here...</small></h1>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse" data-sortable-id="ui-widget-4">
            <div class="panel-heading">
                <h4 class="panel-title">Liste des articles</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12 text-center">
                    <a href="<?php echo $this->url('admin/articles', ['action' => 'add']); ?>" class="btn btn-success btn-lg">Ajouter un article</a>
                </div>
                <div class="col-md-12">
                    <?php

                    if ($this->flashMessenger()->hasMessages()) {
                        echo '<div class="alert alert-success" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>';
                        $messages = $this->flashMessenger()->getMessages();
                        foreach($messages as $message) {
                            echo $message;
                        }
                        echo '</div>';
                    }
                    ?>
                    <table class="table display" id="table_log">
                        <thead>
                        <tr>
                            <th>Image</th>
                            <th>Titre</th>
                            <th>Date de création</th>
                            <th>Etat</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($articles as $key => $article) : ?>
                            <tr>
                                <td><img src="<?php echo $article->getImage() ?>" width="140px" height="140px" class="img-rounded" alt=""></td>
                                <td><?php echo $this->escapeHtml($article->getTitle());?></td>
                                <td><?php echo $article->getDate()->format('d F Y')?></td>
                                <td>
                                    <?php if ($article->isState()) : ?>
                                        <label class="label label-success">Publié</label>
                                    <?php else : ?>
                                        <label class="label label-warning">Désactivé</label>
                                    <?php endif ; ?>
                                </td>
                                <td><a href="<?php echo $this->url('article', ['action' => 'slug', 'id' => $article->getSlug()]); ?>" class="btn btn-inverse"><i class="fa fa-eye"></i></a>
                                    <a href="<?php echo $this->url('admin/articles', ['action' => 'edit', 'id' => $article->getId()]); ?>"
                                       class="btn btn-warning">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a href="javascript:;"
                                       data-toggle="modal"
                                       data-target="<?php echo $this->escapeHtml('#'.$article->getId());?>"
                                       class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>

                            <!-- Modal -->
                            <div class="modal fade" id="<?php echo $this->escapeHtml($article->getId());?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">Supprimer un article</h4>
                                        </div>
                                        <div class="modal-body">
                                            <form method="post" action="<?php echo $this->url('admin/articles', ['action' => 'delete', 'id' => $article->getId()]); ?>">
                                                <p>Etes vous sur de vouloir supprimer l'article <strong><?php echo $this->escapeHtml($article->getTitle());?></strong> ?</p>
                                                <input type="submit" value="OK" class="btn btn-success"/>
                                            </form>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

