<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Articles <small>header small text goes here...</small></h1>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-inverse" data-sortable-id="ui-widget-4">
            <div class="panel-heading">
                <h4 class="panel-title">Liste des articles</h4>
            </div>
            <div class="panel-body">
                <div class="col-md-12 text-center">
                    <a href="<?php echo $this->url('admin/articles', ['action' => 'add']); ?>" class="btn btn-success btn-lg">Ajouter un article</a>
                </div>
                <ul class="result-list">
                    <?php foreach ($articles as $key => $article) : ?>
                        <li>
                        <div class="result-image">
                            <a href="javascript:;"><img src="<?php echo $article->image ?>" alt=""></a>
                        </div>
                        <div class="result-info">
                            <h4 class="title">
                                <a href="javascript:;"><?php echo $this->escapeHtml($article->getTitle());?></a>
                            </h4>

                            <p class="location">United State, BY 10089</p>
                            <p class="desc">
                                <?php echo $this->escapeHtml($article->getContent());?>
                                Le Lorem Ipsum est simplement du faux texte employé dans
                                la composition et la mise en page avant impression. Le Lorem Ip
                                sum est le faux texte standard de
                                l'imprimerie depuis les années 1500, quand un peintre an
                            </p>
                            <div class="btn-row">
                                <a title="" data-original-title="" href="javascript:;" data-toggle="tooltip" data-container="body" data-title="Analytics"><i class="fa fa-fw fa-bar-chart-o"></i></a>
                                <a title="" data-original-title="" href="javascript:;" data-toggle="tooltip" data-container="body" data-title="Tasks"><i class="fa fa-fw fa-tasks"></i></a>
                                <a title="" data-original-title="" href="javascript:;" data-toggle="tooltip" data-container="body" data-title="Configuration"><i class="fa fa-fw fa-cog"></i></a>
                                <a title="" data-original-title="" href="javascript:;" data-toggle="tooltip" data-container="body" data-title="Performance"><i class="fa fa-fw fa-tachometer"></i></a>
                                <a title="" data-original-title="" href="javascript:;" data-toggle="tooltip" data-container="body" data-title="Users"><i class="fa fa-fw fa-user"></i></a>
                            </div>
                        </div>
                        <div class="result-price">
                            <a href="javascript:;" class="btn btn-inverse"><i class="fa fa-eye"></i></a>
                            <a href="<?php echo $this->url('admin/articles', ['action' => 'edit', 'id' => $article->getId()]); ?>"
                               class="btn btn-warning">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="javascript:;"
                               data-toggle="modal"
                               data-target="<?php echo $this->escapeHtml('#'.$article->getId());?>"
                               class="btn btn-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                        </div>
                    </li>
                        <!-- Modal -->
                        <div class="modal fade" id="<?php echo $this->escapeHtml($article->getId());?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Supprimer un article</h4>
                                    </div>
                                    <div class="modal-body">
                                        <form method="post" action="<?php echo $this->url('admin/articles', ['action' => 'delete', 'id' => $article->getId()]); ?>">
                                            <p>Etes vous sur de vouloir supprimer l'article <strong><?php echo $this->escapeHtml($article->getTitle());?></strong> ?</p>
                                            <input type="submit" value="OK" class="btn btn-success"/>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </ul>
        </div>
    </div>

</div>

