<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Login') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- CSS -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('assets/admin/css/default.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/style-responsive.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/style.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/animate.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('assets/admin/css/jquery-ui.min.css'))
        ; ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/admin/js/pace.min.js'))
        ; ?>

    </head>
    <body class="pace-top">

        <div class="login-cover">
        <div class="login-cover-image"><img src="assets/img/login-bg/bg-1.jpg" data-id="login-cover-image" alt="" /></div>
        <div class="login-cover-bg"></div>
    </div>

        <div id="page-container" class="fade">
        <!-- begin login -->
        <div class="login login-v2" data-pageload-addclass="animated fadeIn">
            <!-- begin brand -->
            <div class="login-header">
                <div class="brand">
                    <span class="logo"></span> Sport Blog
                    <small>responsive bootstrap 3 admin template</small>
                </div>
                <div class="icon">
                    <i class="fa fa-sign-in"></i>
                </div>
            </div>
            <!-- end brand -->
            <div class="login-content">
                <?php echo $this->content; ?>
                <form action="index.html" method="POST" class="margin-bottom-0">
                    <div class="form-group m-b-20">
                        <input type="text" class="form-control input-lg" placeholder="Email Address" />
                    </div>
                    <div class="form-group m-b-20">
                        <input type="text" class="form-control input-lg" placeholder="Password" />
                    </div>
                    <div class="checkbox m-b-20">
                        <label>
                            <input type="checkbox" /> Remember Me
                        </label>
                    </div>
                    <div class="login-buttons">
                        <button type="submit" class="btn btn-success btn-block btn-lg">Sign me in</button>
                    </div>
                </form>
            </div>
        </div>
        <!-- end login -->
    </div>

        <!-- JS -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/admin/js/apps.min.js'))
            ->prependFile($this->basePath('assets/admin/js/login-v2.demo.min.js'))
            ->prependFile($this->basePath('assets/admin/js/jquery.cookie.js'))
            ->prependFile($this->basePath('assets/admin/js/jquery.slimscroll.min.js'))
            ->prependFile($this->basePath('assets/admin/js/bootstrap.min.js'))
            ->prependFile($this->basePath('assets/admin/js/jquery-ui.min.js'))
            ->prependFile($this->basePath('assets/admin/js/jquery-migrate-1.1.0.min.js'))
            ->prependFile($this->basePath('assets/admin/js/jquery-1.9.1.min.js'))
        ; ?>

        <script>
            $(document).ready(function() {
                App.init();
                LoginV2.init();
            });
        </script>

        <?php echo $this->inlineScript() ?>
    </body>
</html>
