<li>
    <!-- begin comment-avatar -->
    <div class="comment-avatar">
        <i class="fa fa-user"></i>
    </div>
    <!-- end comment-avatar -->
    <!-- begin comment-container -->
    <div class="comment-container">
        <div class="comment-author">
            <?php echo $this->escapeHtml($object->getName());?>
            <span class="comment-date">
                on <span class="underline"><?php echo $object->getDate()->format('d F Y');?></span>
            </span>
        </div>
        <div class="comment-content">
            <?php echo $this->escapeHtml($object->getContent());?>
        </div>
    </div>
    <!-- end comment-container -->
</li>