<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Logs</h1>

<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse" data-sortable-id="table-basic-1">
            <div class="panel-heading">
                <h4 class="panel-title">Liste des dernières entrées</h4>
            </div>
            <div class="panel-body">
                <?php

                if ($this->flashMessenger()->hasMessages())
                {
                    echo '<div class="alert alert-success" role="alert">';
                    echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>';
                    $messages = $this->flashMessenger()->getMessages();
                    foreach ($messages as $message)
                    {
                        echo $message;
                    }
                    echo '</div>';
                }
                ?>
                <table class="table display" id="table_log">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Description</th>
                        <th>Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($logs as $key => $log) : ?>
                        <tr>
                            <td><?php echo $key + 1; ?></td>
                            <td><?php echo $log->getDescription() ?></td>
                            <td><?php echo $log->getDate()->format('d F Y H:i:s') ?></td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
            </div>
        </div>
    </div>
</div>