<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>

<?php echo $this->form()->openTag($form) ?>
<?php foreach ($form as $element): ?>
    <?php if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button): ?>
        <div class="form-group m-b-20">
            <?php  if ($element->getLabel() === 'Email'): ?>
                <?php $element->setAttribute('placeholder', 'Email') ?>
            <?php elseif ($element->getLabel() === 'Password'): ?>
                <?php $element->setAttribute('placeholder', 'Password') ?>
            <?php endif ;?>
                <?php $element->setAttribute('class', 'form-control input-lg') ?>
                <?php echo $this->formElement($element) . $this->formElementErrors($element); ?>
        </div>
        <?php else: ?>
        <div class="login-buttons">
            <?php $element->setAttribute('class', 'btn btn-success btn-block btn-lg') ?>
            <?php echo $this->formElement($element) . $this->formElementErrors($element) ?>
        </div>
    <?php endif ;?>
<?php endforeach ;?>
<?php echo $this->form()->closeTag() ?>
