<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Blog') ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- styles -->
        <?php echo $this->partial('/partials/global-css.phtml'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('assets/front/js/pace.min.js'))
        ; ?>

    </head>
    <body style="background-color: <?php echo $this->backgroundColor(); ?>;">
        <!-- Header -->
        <?php echo $this->partial('/partials/header.phtml'); ?>

        <!-- Cover -->
        <?php echo $this->partial('/partials/cover.phtml'); ?>

        <!-- Content -->
        <div id="content" class="content">
            <div class="container">
                <!-- begin row -->
                <div class="row row-space-30">

                    <!-- Content -->
                    <?php echo $this->content; ?>

                    <!-- Sidebar -->
                    <?php echo $this->partial('/partials/sidebar.phtml'); ?>

                </div>
                <!-- end row -->
            </div>
        </div>

        <!-- Footer -->
        <?php echo $this->partial('/partials/footer.phtml'); ?>

        <!-- Javascript -->
        <?php echo $this->partial('/partials/global-js.phtml'); ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
