<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboardd</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Dashboardd</h1>
<div class="row">
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-green">
            <div class="stats-icon"><i class="fa fa-pencil"></i></div>
            <div class="stats-info">
                <h4>ARTICLES</h4>
                <p><?php echo count($articles); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-blue">
            <div class="stats-icon"><i class="fa fa-comments"></i></div>
            <div class="stats-info">
                <h4>COMMENTAIRES</h4>
                <p><?php echo count($comments); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-purple">
            <div class="stats-icon"><i class="fa fa-tags"></i></div>
            <div class="stats-info">
                <h4>CATEGORIES</h4>
                <p><?php echo count($categories); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-red">
            <div class="stats-icon"><i class="fa fa-clock-o"></i></div>
            <div class="stats-info">
                <h4>AVG TIME ON SITE</h4>
                <p>00:12:23</p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
</div>

<div class="row">
    <div class="col-md-8 ui-sortable">
        <!-- begin panel -->
        <div class="panel panel-inverse panel-with-tabs" data-sortable-id="ui-unlimited-tabs-1">
            <div class="panel-heading p-0">
                <div class="panel-heading-btn m-r-10 m-t-10">
                </div>
                <!-- begin nav-tabs -->
                <div class="tab-overflow overflow-right">
                    <ul class="nav nav-tabs nav-tabs-inverse">
                        <li class="active"><a aria-expanded="true" href="#nav-tab-1" data-toggle="tab">5 derniers commentaires</a></li>
                        <li class=""><a aria-expanded="false" href="#nav-tab-2" data-toggle="tab">5 derniers articles</a></li>
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="nav-tab-1">
                    <ul class="media-list media-list-with-divider">
                        <?php foreach ($lastFiveComments as $lastFiveComment) : ?>
                        <li class="media media-sm">
                            <div href="javascript:;" class="pull-right">
                                <button href="#"
                                        class="btn btn-success">
                                    <i class="fa fa-eye"></i>
                                </button>
                                <button href="#"
                                        data-toggle="modal"
                                        data-target="#"
                                        class="btn btn-danger">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </div>
                            <div class="media-body">
                                <a href="javascript:;">
                                    <h5 class="media-heading">
                                    <?php echo $lastFiveComment->getName(); ?>
                                    <?php if ($lastFiveComment->isState()) : ?>
                                        <label class="label label-success">Approuvé</label>
                                        <i class="fa fa-check text-success"></i>
                                    <?php else : ?>
                                        <label class="label label-warning">Non approuvé</label>
                                        <i class="fa fa-close text-warning"></i>
                                    <?php endif ; ?>
                                    </h5>
                                </a>
                                <p class="m-b-5"><?php echo mb_strimwidth($lastFiveComment->getContent(),0,150, "...");?></p>
                                <i class="text-muted">Received on <?php echo $lastFiveComment->getDate()->format('d F Y'); ?></i>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <div class="tab-pane fade" id="nav-tab-2">
                    <ul class="media-list media-list-with-divider">
                        <?php foreach ($lastFiveArticles as $lastFiveArticle) : ?>
                            <li class="media media-sm">
                                <div href="javascript:;" class="pull-right">
                                    <button href="#"
                                       class="btn btn-warning">
                                        <i class="fa fa-edit"></i>
                                    </button>
                                    <button href="#"
                                       data-toggle="modal"
                                       data-target="#"
                                       class="btn btn-danger">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </div>
                                <div class="media-body">
                                    <a href="javascript:;"><h4 class="media-heading"><?php echo $lastFiveArticle->getTitle(); ?></h4></a>
                                    <p class="m-b-5"><?php echo mb_strimwidth($lastFiveArticle->getContent(),0,150, "...");?></p>
                                </div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
</div>
