<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboardd</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Dashboardd</h1>
<div class="row">
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-green">
            <div class="stats-icon"><i class="fa fa-pencil"></i></div>
            <div class="stats-info">
                <h4>ARTICLES</h4>
                <p><?php echo count($articles); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-blue">
            <div class="stats-icon"><i class="fa fa-comments"></i></div>
            <div class="stats-info">
                <h4>COMMENTAIRES</h4>
                <p><?php echo count($comments); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-purple">
            <div class="stats-icon"><i class="fa fa-tags"></i></div>
            <div class="stats-info">
                <h4>CATEGORIES</h4>
                <p><?php echo count($categories); ?></p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
    <!-- begin col-3 -->
    <div class="col-md-3 col-sm-6">
        <div class="widget widget-stats bg-red">
            <div class="stats-icon"><i class="fa fa-clock-o"></i></div>
            <div class="stats-info">
                <h4>AVG TIME ON SITE</h4>
                <p>00:12:23</p>
            </div>
            <div class="stats-link">
                <a href="javascript:;">View Detail <i class="fa fa-arrow-circle-o-right"></i></a>
            </div>
        </div>
    </div>
    <!-- end col-3 -->
</div>

<div class="row">
    <div class="col-md-8 ui-sortable">
        <!-- begin panel -->
        <div class="panel panel-inverse panel-with-tabs" data-sortable-id="ui-unlimited-tabs-1">
            <div class="panel-heading p-0">
                <div class="panel-heading-btn m-r-10 m-t-10">
                </div>
                <!-- begin nav-tabs -->
                <div class="tab-overflow overflow-right">
                    <ul class="nav nav-tabs nav-tabs-inverse">
                        <li class="active"><a aria-expanded="true" href="#nav-tab-1" data-toggle="tab">5 derniers commentaires</a></li>
                        <li class=""><a aria-expanded="false" href="#nav-tab-2" data-toggle="tab">5 derniers articles</a></li>
                    </ul>
                </div>
            </div>
            <div class="tab-content">
                <div class="tab-pane fade active in" id="nav-tab-1">
                    <h3 class="m-t-10">TODO</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Integer ac dui eu felis hendrerit lobortis. Phasellus elementum, nibh eget adipiscing porttitor,
                        est diam sagittis orci, a ornare nisi quam elementum tortor.
                        Proin interdum ante porta est convallis dapibus dictum in nibh.
                        Aenean quis massa congue metus mollis fermentum eget et tellus.
                        Aenean tincidunt, mauris ut dignissim lacinia, nisi urna consectetur sapien,
                        nec eleifend orci eros id lectus.
                    </p>
                </div>
                <div class="tab-pane fade" id="nav-tab-2">
                    <h3 class="m-t-10">TODO</h3>
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        Integer ac dui eu felis hendrerit lobortis. Phasellus elementum, nibh eget adipiscing porttitor,
                        est diam sagittis orci, a ornare nisi quam elementum tortor.
                        Proin interdum ante porta est convallis dapibus dictum in nibh.
                        Aenean quis massa congue metus mollis fermentum eget et tellus.
                        Aenean tincidunt, mauris ut dignissim lacinia, nisi urna consectetur sapien,
                        nec eleifend orci eros id lectus.
                    </p>
                    <p>
                        Aenean eget odio eu justo mollis consectetur non quis enim.
                        Vivamus interdum quam tortor, et sollicitudin quam pulvinar sit amet.
                        Donec facilisis auctor lorem, quis mollis metus dapibus nec. Donec interdum tellus vel mauris vehicula,
                        at ultrices ex gravida. Maecenas at elit tincidunt, vulputate augue vitae, vulputate neque.
                        Aenean vel quam ligula. Etiam faucibus aliquam odio eget condimentum.
                        Cras lobortis, orci nec eleifend ultrices, orci elit pellentesque ex, eu sodales felis urna nec erat.
                        Fusce lacus est, congue quis nisi quis, sodales volutpat lorem.
                    </p>
                </div>
            </div>
        </div>
        <!-- end panel -->
    </div>
</div>
