<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Categories</h1>

<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse" data-sortable-id="table-basic-1">
            <div class="panel-heading">
                <h4 class="panel-title">Liste des catégories</h4>
            </div>
            <div class="panel-body">
                <?php

                if ($this->flashMessenger()->hasMessages()) {
                    echo '<div class="alert alert-success" role="alert">';
                    echo '<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>';
                    $messages = $this->flashMessenger()->getMessages();
                    foreach($messages as $message) {
                        echo $message;
                    }
                    echo '</div>';
                }
                ?>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Nom</th>
                        <th>Slug</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($categories as $key => $category) : ?>
                        <tr>
                            <td><?php echo $key+1 ;?></td>
                            <td><?php echo $this->escapeHtml($category->name);?></td>
                            <td><?php echo $this->escapeHtml($category->slug);?></td>
                            <td>
                                <a href="<?php echo $this->url('admin/categories', ['action' => 'edit', 'id' => $category->id]); ?>"
                                   class="btn btn-warning">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="javascript:;"
                                   data-toggle="modal"
                                   data-target="<?php echo $this->escapeHtml('#'.$category->id);?>"
                                   class="btn btn-danger">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>

                        <!-- Modal -->
                        <div class="modal fade" id="<?php echo $this->escapeHtml($category->id);?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Supprimer une catégorie</h4>
                                    </div>
                                    <div class="modal-body">
                                        <p>Etes vous sur de vouloir supprimer la catégorie <strong><?php echo $this->escapeHtml($category->name);?></strong> ?</p>
                                        <a href="<?php echo $this->url('admin/categories', ['action' => 'delete', 'id' => $category->id]); ?>" class="btn btn-success">Ok</a>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <?php endforeach; ?>
                    </tbody>
                </table>
                <a href="<?php echo $this->url('admin/categories', ['action' => 'add']); ?>" class="btn btn-success m-r-5 m-b-5"">Ajouter</a>
            </div>
        </div>
    </div>
</div>
