<div id="footer" class="footer">
    <!-- begin container -->
    <div class="container">
        <!-- begin row -->
        <div class="row">
            <!-- begin col-3 -->
            <div class="col-md-3 col-sm-3">
                <!-- begin section-container -->
                <div class="section-container">
                    <h4 class="footer-title">Categories</h4>
                    <ul class="categories">
                        <?php echo $this->categoryFooter(); ?>
                    </ul>
                </div>
                <!-- end section-container -->
            </div>
            <div class="col-md-3 col-sm-3">
                <!-- begin section-container -->
                <div class="section-container">
                    <h4 class="footer-title">Recent Posts</h4>
                    <ul class="recent-post">
                        <?php echo $this->recentArticleFooter(); ?>
                    </ul>
                </div>
                <!-- end section-container -->
            </div>
            <!-- end col-3 -->
            <!-- begin col-3 -->
            <div class="col-md-3 col-sm-3">
                <div class="section-container">
                    <h4 class="footer-title">Contact</h4>
                    <address>
                        <strong>Blog Snow</strong><br />
                        795 Folsom Ave, Suite 600<br />
                        San Francisco, CA 94107<br />
                        P: (123) 456-7890<br />
                        <br />
                        <strong>Full Name</strong><br />
                        <a href="#">blog-snow@example.com</a>
                    </address>
                </div>
                <!-- end section-container -->
            </div>
            <!-- end col-3 -->
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</div>