<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('front/css/theme/default.css'))
    ->prependStylesheet($this->basePath('front/css/style-responsive.css'))
    ->prependStylesheet($this->basePath('front/css/style.css'))
    ->prependStylesheet($this->basePath('front/css/animate.css'))
    ->prependStylesheet($this->basePath('front/css/bootstrap.min.css'))?>