<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('assets/front/css/theme/default.css'))
    ->prependStylesheet($this->basePath('assets/front/css/style-responsive.css'))
    ->prependStylesheet($this->basePath('assets/front/css/style.css'))
    ->prependStylesheet($this->basePath('assets/front/css/animate.css'))
    ->prependStylesheet($this->basePath('assets/front/css/bootstrap.min.css'))?>