<div class="col-md-3">
    <!-- end section-container -->
    <!-- begin section-container -->
    <div class="section-container">
        <h4 class="section-title"><span>Categories</span></h4>
        <ul class="sidebar-list">
            <?php echo $this->categoryWidget(); ?>
        </ul>
    </div>
    <!-- end section-container -->
    <!-- begin section-container -->
    <div class="section-container">
        <h4 class="section-title"><span>Recent Post</span></h4>
        <ul class="sidebar-recent-post">
            <?php echo $this->recentArticleWidget(); ?>
        </ul>
    </div>
    <!-- end section-container -->
    <!-- begin section-container -->
    <div class="section-container">
        <h4 class="section-title"><span>Follow Us</span></h4>
        <ul class="sidebar-social-list">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-instagram"></i></a></li>

        </ul>
    </div>
    <!-- end section-container -->
</div>