<?php
echo $this->partial('/partials/breadcrumb.phtml', [
        'links' => [
            'Home' => $this->url('blog'),
            $category->getName() => null,
        ]
    ]
);
?>

<div class="col-md-9">
<!-- begin post-list -->
<ul class="post-list">
    <?php
        if (empty($articles)) {
            echo '<p>Aucun article disponible dans cette catégorie</p>';
        } else {
            $this->partialLoop()->setObjectKey('object');
            echo $this->partialLoop('/partials/article.phtml', $articles);
        }
    ?>
</ul>
<!-- end post-list -->

    <div class="section-container">
        <!-- begin pagination -->
        <div class="pagination-container text-center">
            <ul class="pagination m-t-0 m-b-0">
                <li><a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['first']])?>">First</a></li>
                <li class="<?php echo $pagination['previous'] == null ? 'disabled' : '' ?>">
                    <?php if (isset($pagination['previous'])): ?>
                        <a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['previous']])?>">Previous</a>
                    <?php else: ?>
                        <span class="text">Previous</span>
                    <?php endif; ?>
                </li>
                <?php if(isset($pagination['previous'])): ?>
                    <li><a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['previous']])?>"><?= $pagination['previous'] ?></a></li>
                <?php endif; ?>
                <li class="active"><a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['current']])?>"><?php echo $pagination['current'] ?></a></li>
                <?php if(isset($pagination['next'])): ?>
                    <li><a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['next']])?>"><?= $pagination['next'] ?></a></li>
                <?php endif; ?>
                <li class="<?php echo $pagination['next'] == null ? 'disabled' : '' ?>">
                    <?php if (isset($pagination['next'])): ?>
                        <a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['next']])?>">Next</a>
                    <?php else: ?>
                        <span class="text">Next</span>
                    <?php endif; ?>
                </li>
                <li><a href="<?= $this->Url('category', ['slug' => $category->getSlug(), 'page' => $pagination['last']])?>">Last</a></li>
            </ul>
        </div>
        <!-- end pagination -->
    </div>
</div>
