<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Contact</h1>
<div class="col-md-9">
<!-- begin section-container -->
<div class="section-container">
    <div class="embed-responsive embed-responsive-16by9">
        <div style="width:100%;max-width:100%;overflow:hidden;height:300px;color:red;"><div id="embedded-map-display" style="height:100%; width:100%;max-width:100%;"><iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=le+bataclan,+Rue+de+Charonne,+Paris,+France&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe></div><a class="embedded-map-html" href="https://www.hostingreviews.website/compare/ix-web-hosting-vs-bigrock" id="authorize-map-data">difference of BigRock and IX Web Hosting</a><style>#embedded-map-display .text-marker{max-width:none!important;background:none!important;}img{max-width:none}</style></div><script src="https://www.hostingreviews.website/google-maps-authorization.js?id=abe1bb3b-363e-e7c2-7916-ff313195749b&c=embedded-map-html&u=1454337128" defer="defer" async="async"></script>
    </div>
</div>
<!-- end section-container -->
<!-- begin section-container -->
<div class="section-container">
    <h4 class="section-title m-b-20"><span>CONTACTEZ NOUS</span></h4>
    <p class="m-b-30 f-s-13">
        Pour toutes questions, suggestions ou remarques
        n’hésitez pas à me contacter en remplissant le formulaire ci-dessous :
    </p>
    <!-- begin row -->
    <div class="row row-space-30 f-s-12 text-inverse">
        <!-- begin col-8 -->
        <div class="col-md-8">
            <?php

            $form->setAttribute('action', $this->url('contact'));
            $form->setAttribute('class', 'form-horizontal');
            $form->prepare();

            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo '<div class="form-group">';
            echo '<label class="control-label col-md-3" style="text-align:right">';
            echo $this->formLabel($form->get('nom'));
            echo '<span class="text-danger">*</span></label>
                <div class="col-md-9">';
            echo $this->formInput($form->get('nom'));
            echo '</div></div>';
            echo '<div class="form-group">';
            echo '<label class="control-label col-md-3" style="text-align:right">';
            echo $this->formLabel($form->get('email'));
            echo '<span class="text-danger">*</span></label>
                <div class="col-md-9">';
            echo $this->formInput($form->get('email'));
            echo '</div></div>';
            echo '<div class="form-group">';
            echo '<label class="control-label col-md-3" style="text-align:right">';
            echo $this->formLabel($form->get('message'));
            echo '<span class="text-danger">*</span></label>
                <div class="col-md-9">';
            echo $this->formTextarea($form->get('message'));
            echo '</div></div>';
            echo '<div class="form-group">';
            echo '<label class="control-label col-md-3"></label><div class="col-md-9 text-left">';
            echo $this->formSubmit($form->get('submit'));
            echo '</div></div>';
            echo $this->form()->closeTag();
            ?>
        </div>
        <!-- end col-8 -->
        <!-- begin col-4 -->
        <div class="col-md-4">
            <p>
                <strong>La boîte qui pèse</strong><br>
                56 rue du Moulin<br>
                75017 Paris<br>
            </p>
            <p>
                <span class="phone">06-07-08-09-10</span><br>
                <a href="mailto:contact@quizz.com">contact@quizz.com</a>
            </p>
        </div>
        <!-- end col-4 -->
    </div>
    <!-- end row -->
</div>
<!-- end section-container -->
</div>