<div class="col-md-9">
    <!-- begin post-detail -->
    <div class="post-detail section-container">
        <?php
            echo $this->partial('/partials/breadcrumb.phtml', [
                    'links' => [
                        'Home' => $this->url('blog'),
                        $article->getCategory()->getName() => $this->url('category', ['slug' => $article->getCategory()->getSlug()]),
                        $article->getTitle() => null
                    ]
                ]
            );
        ?>
        <h4 class="post-title">
            <a href="post_detail.html"><?php echo $this->escapeHtml($article->getTitle());?></a>
        </h4>
        <div class="post-by">
            <?php echo $article->getDate()->format('d F Y') ;?> <span class="divider">|</span> <a href="#">Sports</a>, <a href="#">Mountain</a>, <a href="#">Bike</a> <span class="divider">|</span> 2 Comments
        </div>

        <div class="post-image">
            <img src="assets/img/post1.jpg" alt="" />
        </div>

        <div class="post-desc">
            <?php echo $article->getContent();?>
        </div>

    </div>
    <!-- end post-detail -->

    <!-- begin section-container -->
    <div class="section-container">
        <h4 class="section-title"><span>Tous les commentaires (<?php echo count($comments);?>)</span></h4>
        <!-- begin comment-list -->
        <ul class="comment-list">
            <?php
                $this->partialLoop()->setObjectKey('object');
                echo $this->partialLoop('/partials/comment.phtml', $comments)
            ?>
        </ul>
        <!-- end comment-list -->
    </div>
    <!-- end section-container -->

    <!-- begin section-container -->
    <div class="section-container">
        <h4 class="section-title m-b-20"><span>Ajouter un commentaire</span></h4>
        <?php
        $commentForm->setAttribute('action', $this->url('article', ['action' => 'show', 'slug' => $article->getSlug()]));
        $commentForm->setAttribute('class', 'form-horizontal');
        $commentForm->prepare();

        echo $this->form()->openTag($commentForm);
        echo $this->formHidden($commentForm->get('id'));
        echo $this->formHidden($commentForm->get('article')->setAttribute('value', $article->getId()));
        ?>
        <div class="form-group">
            <label class="control-label f-s-12 col-md-2"><?php echo $this->formLabel($commentForm->get('name')) ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-10">
                <?php echo $this->formInput($commentForm->get('name')) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label f-s-12 col-md-2"><?php echo $this->formLabel($commentForm->get('email')) ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-10">
                <?php echo $this->formInput($commentForm->get('email')) ?>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label f-s-12 col-md-2"><?php echo $this->formLabel($commentForm->get('content')) ?>
                <span class="text-danger">*</span>
            </label>
            <div class="col-md-10">
                <?php echo $this->formTextarea($commentForm->get('content')) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <?php echo $this->formSubmit($commentForm->get('submit'));?>
            </div>
        </div>

        <?php
            $this->form()->closeTag();
        ?>

    </div>
    <!-- end section-container -->
</div>