<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath('assets/admin/css/style.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/bootstrap-colorpicker.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/jquery.gritter.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/dataTables.bootstrap.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/jquery.dataTables.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/jquery-jvectormap-1.2.2.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/default.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/style-responsive.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/style.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/animate.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/font-awesome.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/bootstrap.min.css'))
    ->prependStylesheet($this->basePath('assets/admin/css/jquery-ui.min.css'))
; ?>