<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Commentaires</h1>

<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse" data-sortable-id="table-basic-1">
            <div class="panel-heading">
                <h4 class="panel-title">Liste des commentaires</h4>
            </div>
        </div>
    </div>
</div>
