<!-- begin breadcrumb -->
<ol class="breadcrumb pull-right">
    <li><a href="javascript:;">Home</a></li>
    <li class="active">Dashboard</li>
</ol>
<!-- end breadcrumb -->
<!-- begin page-header -->
<h1 class="page-header">Commentaires</h1>

<div class="row">
    <div class="col-md-12 ui-sortable">
        <div class="panel panel-inverse" data-sortable-id="table-basic-1">
            <div class="panel-heading">
                <h4 class="panel-title">Détail d'un commentaire</h4>
            </div>
            <div class="panel-body">
                <p>Name: <?php echo $comment->name?></p>
                <p>email: <?php echo $comment->email?></p>
                <p>content: <?php echo $comment->content?></p>

                <?php

                $commentForm->setAttribute('action', $this->url('admin/comment', [
                        'action' => 'show',
                        'id'     => $comment->getId()
                    ]
                ));
                $commentForm->prepare();

                echo $this->form()->openTag($commentForm);
                echo $this->formHidden($commentForm->get('id'));
                echo '<div class="form-group">';
                echo $this->formLabel($commentForm->get('state'));
                echo $this->formInput($commentForm->get('state'));
                echo '</div>';
                echo '<div class="form-group">';
                echo $this->formSubmit($commentForm->get('submit'));
                echo '</div>';
                echo $this->form()->closeTag();
                ?>

            </div>
        </div>
    </div>
</div>
